INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(1,TRUE,'ILGALAIKIS TURTAS','1','','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Nematerialusis turtas','11','1','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Plėtros darbai','111','11','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Plėtros darbų atlikimo savikaina','1110','111','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Plėtros darbų vertės amortizacija (−)','1118','111','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Plėtros darbų vertės sumažėjimas (−)','1119','111','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Prestižas','112','11','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Prestižo įsigijimo savikaina','1120','112','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Prestižo vertės amortizacija (−)','1128','112','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Prestižo vertės sumažėjimas (−)','1129','112','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Programinė įranga','113','11','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Programinės įrangos įsigijimo savikaina','1130','113','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Programinės įrangos vertės amortizacija (−)','1138','113','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Programinės įrangos vertės sumažėjimas (−)','1139','113','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Koncesijos, patentai, licencijos, prekių ženklai ir panašios teisės','114','11','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Koncesijų, patentų, licencijų, prekių ženklų ir panašių teisių įsigijimo savikaina','1140','114','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Koncesijų, patentų, licencijų, prekių ženklų ir panašių teisių vertės amortizacija (−)','1148','114','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Koncesijų, patentų, licencijų, prekių ženklų ir panašių teisių vertės sumažėjimas (−)','1149','114','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kitas nematerialusis turtas','115','11','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito nematerialiojo turto įsigijimo savikaina','1150','115','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito nematerialiojo turto vertės amortizacija (−)','1158','115','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito nematerialiojo turto vertės sumažėjimas (−)','1159','115','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Sumokėti avansai už nematerialųjį turtą','116','11','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Materialusis turtas','12','1','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Žemė','120','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žemės įsigijimo savikaina','1200','120','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žemės vertės pokytis dėl perkainojimo','1201','120','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žemės vertės sumažėjimas (−)','1209','120','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Pastatai ir statiniai','121','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pastatų ir statinių įsigijimo savikaina','1210','121','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pastatų ir statinių vertės pokytis dėl perkainojimo','1211','121','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ruošiami naudoti pastatai ir statiniai','1212','121','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pastatų ir statinių įsigijimo savikainos nusidėvėjimas (−)','1217','121','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pastatų ir statinių vertės pokyčio dėl perkainojimo nusidėvėjimas (−)','1218','121','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pastatų ir statinių vertės sumažėjimas (−)','1219','121','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Mašinos ir įranga','122','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mašinų ir įrangos įsigijimo savikaina','1220','122','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mašinų ir įrangos vertės pokytis dėl perkainojimo','1221','122','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ruošiamos naudoti mašinos ir įranga','1222','122','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mašinų ir įrangos įsigijimo savikainos nusidėvėjimas (−)','1227','122','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mašinų ir įrangos vertės pokyčio dėl perkainojimo nusidėvėjimas (−)','1228','122','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mašinų ir įrangos vertės sumažėjimas (−)','1229','122','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Transporto priemonės','123','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Transporto priemonių įsigijimo savikaina','1230','123','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Transporto priemonių vertės pokytis dėl perkainojimo','1231','123','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ruošiamos naudoti transporto priemonės','1232','123','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Transporto priemonių įsigijimo savikainos nusidėvėjimas (−)','1237','123','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Transporto priemonių vertės pokyčio dėl perkainojimo nusidėvėjimas (−)','1238','123','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Transporto priemonių vertės sumažėjimas (−)','1239','123','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kiti įrenginiai, prietaisai ir įrankiai','124','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų įrenginių, prietaisų ir įrankių įsigijimo savikaina','1240','124','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų įrenginių, prietaisų ir įrankių vertės pokytis dėl perkainojimo','1241','124','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ruošiami naudoti kiti įrenginiai, prietaisai ir įrankiai','1242','124','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų įrenginių, prietaisų ir įrankių įsigijimo savikainos nusidėvėjimas (−)','1247','124','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų įrenginių, prietaisų ir įrankių vertės pokyčio dėl perkainojimo nusidėvėjimas (−)','1248','124','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų įrenginių, prietaisų ir įrankių vertės sumažėjimas (−)','1249','124','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Investicinis turtas','125','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Žemė, kaip investicinis turtas','1250','125','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Žemės, kaip investicinio turto, įsigijimo savikaina','12500','1250','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Žemės, kaip investicinio turto, tikrosios vertės pokytis (+/−)','12503','1250','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Žemės, kaip investicinio turto, vertės sumažėjimas (−)','12509','1250','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Pastatai, kaip investicinis turtas','1251','125','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pastatų, kaip investicinio turto, įsigijimo savikaina','12510','1251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pastatų, kaip investicinio turto, tikrosios vertės pokytis (+/−)','12513','1251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pastatų, kaip investicinio turto, įsigijimo savikainos nusidėvėjimas (−)','12517','1251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pastatų, kaip investicinio turto, vertės sumažėjimas (−)','12519','1251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Sumokėti avansai ir vykdomi materialiojo turto statybos (gamybos) darbai','126','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Sumokėti avansai už ilgalaikį materialųjį turtą','1260','126','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Vykdomi materialiojo turto statybos (gamybos) darbai','1261','126','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Statomas (gaminamas) ar rekonstruojamas ilgalaikis materialusis turtas','12610','1261','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Statomo (gaminamo) ar rekonstruojamo ilgalaikio materialiojo turto vertės pokytis dėl perkainojimo','12611','1261','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Statomo ar rekonstruojamo ilgalaikio materialiojo turto vertės sumažėjimas (−)','12619','1261','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Turtas, kuris pagal įstatymus gali būti tik valstybės nuosavybė','127','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Turto, kuris pagal įstatymus gali būti tik valstybės nuosavybė, įsigijimo savikaina','1270','127','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Turto, kuris pagal įstatymus gali būti tik valstybės nuosavybė, vertės pokytis dėl perkainojimo','1271','127','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ruošiamas naudoti turtas, kuris pagal įstatymus gali būti tik valstybės nuosavybė','1272','127','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Turto, kuris pagal įstatymus gali būti tik valstybės nuosavybė, įsigijimo savikainos nusidėvėjimas (−)','1277','127','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Turto, kuris pagal įstatymus gali būti tik valstybės nuosavybė, vertės pokyčio dėl perkainojimo nusidėvėjimas (−)','1278','127','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Turto, kuris pagal įstatymus gali būti tik valstybės nuosavybė, vertės sumažėjimas (−)','1279','127','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Centralizuotai valdomas valstybės turtas','128','12','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Centralizuotai valdomo valstybės turto įsigijimo savikaina','1280','128','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Centralizuotai valdomo valstybės turto vertės pokytis dėl perkainojimo','1281','128','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ruošiamas naudoti centralizuotai valdomas valstybės turtas','1282','128','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Centralizuotai valdomo valstybės turto įsigijimo savikainos nusidėvėjimas (−)','1287','128','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Centralizuotai valdomo valstybės turto vertės pokyčio dėl perkainojimo nusidėvėjimas (−)','1288','128','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Centralizuotai valdomo valstybės turto vertės sumažėjimas (−)','1289','128','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Finansinis turtas','16','1','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įmonių grupės įmonių akcijos','160','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Patronuojančiosios įmonės akcijų vertė','1600','160','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės akcijų įsigijimo savikaina','16000','1600','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės akcijų vertės sumažėjimas (−)','16009','1600','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Patronuojamųjų įmonių akcijų vertė','1601','160','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių akcijų įsigijimo savikaina','16010','1601','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių akcijų vertės sumažėjimas (−)','16019','1601','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Paskolos įmonių grupės įmonėms','161','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Paskolos patronuojančiajai įmonei','1610','161','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiajai įmonei suteiktų paskolų vertė','16100','1610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiajai įmonei suteiktų paskolų vertės sumažėjimas (−)','16109','1610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Paskolos patronuojamosioms įmonėms','1611','161','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamosioms įmonėms suteiktų paskolų vertė','16110','1611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamosioms įmonėms suteiktų paskolų vertės sumažėjimas (−)','16119','1611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Iš įmonių grupės įmonių gautinos sumos','162','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Iš patronuojančiosios įmonės gautinos sumos','1620','162','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš patronuojančiosios įmonės gautinų sumų vertė','16200','1620','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš patronuojančiosios įmonės gautinų sumų vertės sumažėjimas (−)','16209','1620','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Iš patronuojamųjų įmonių gautinos sumos','1621','162','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš patronuojamųjų įmonių gautinų sumų vertė','16210','1621','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš patronuojamųjų įmonių gautinų sumų vertės sumažėjimas (−)','16219','1621','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Asocijuotųjų įmonių akcijos','163','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Asocijuotųjų įmonių akcijų įsigijimo savikaina','1630','163','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Asocijuotųjų įmonių akcijų vertės sumažėjimas (−)','1639','163','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Paskolos asocijuotosioms įmonėms','164','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Asocijuotosioms įmonėms suteiktų paskolų vertė','1640','164','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Asocijuotosioms įmonėms suteiktų paskolų vertės sumažėjimas (−)','1649','164','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Iš asocijuotųjų įmonių gautinos sumos','165','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš asocijuotųjų įmonių gautinų sumų vertė','1650','165','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš asocijuotųjų įmonių gautinų sumų vertės sumažėjimas (−)','1651','165','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Ilgalaikės investicijos','166','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kitų įmonių nuosavybės vertybiniai popieriai','1660','166','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų įmonių nuosavybės vertybinių popierių įsigijimo savikaina','16600','1660','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų įmonių nuosavybės vertybinių popierių tikrosios vertės pokytis (+/−)','16601','1660','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų įmonių nuosavybės vertybinių popierių vertės sumažėjimas (−)','16609','1660','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Ne nuosavybės vertybiniai popieriai','1661','166','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Iki išpirkimo laikomi ne nuosavybės vertybiniai popieriai','16610','1661','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Iki išpirkimo laikomų ne nuosavybės vertybinių popierių įsigijimo savikaina','166100','16610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Iki išpirkimo laikomų ne nuosavybės vertybinių popierių amortizuotos savikainos pokytis (+/−)','166101','16610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Iki išpirkimo laikomų ne nuosavybės vertybinių popierių vertės sumažėjimas (−)','166109','16610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Kiti ne nuosavybės vertybiniai popieriai','16611','1661','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Kitų ne nuosavybės vertybinių popierių įsigijimo savikaina','166110','16611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Kitų ne nuosavybės vertybinių popierių tikrosios vertės pokytis (+/−)','166111','16611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Kitų ne nuosavybės vertybinių popierių vertės sumažėjimas (−)','166119','16611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kiti vertybiniai popieriai','1664','166','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų vertybinių popierių įsigijimo savikaina','16640','1664','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų vertybinių popierių tikrosios vertės pokytis (+/−)','16641','1664','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų vertybinių popierių vertės sumažėjimas (−)','16649','1664','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Terminuotieji indėliai','1665','166','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Po vienų metų gautinos sumos','167','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Po vienų metų gautinos pirkėjų skolos','1670','167','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Gautinų pirkėjų skolų vertė','16700','1670','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Gautinų pirkėjų skolų vertės sumažėjimas (−)','16709','1670','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Suteiktos paskolos','1671','167','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Suteiktų paskolų vertė','16710','1671','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Suteiktų paskolų sumų vertės sumažėjimas (−)','16719','1671','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Po vienų metų gautinos lizingo (finansinės nuomos) sumos','1672','167','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kitos po vienų metų gautinos sumos','1674','167','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Gautinų sumų vertė','16740','1674','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Gautinų sumų vertės sumažėjimas (−)','16749','1674','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kitas finansinis turtas','168','16','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Sumokėti avansai už finansinį turtą','1680','168','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš išvestinių finansinių priemonių atsiradęs finansinis turtas','1681','168','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kitas ilgalaikis finansinis turtas','1682','168','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kito ilgalaikio finansinio turto įsigijimo savikaina','16820','1682','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kito ilgalaikio finansinio turto tikrosios vertės pokytis (+/−)','16821','1682','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kito ilgalaikio finansinio turto vertės sumažėjimas (−)','16829','1682','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Kitas ilgalaikis turtas','17','1','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Atidėtojo pelno mokesčio turtas','171','17','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Biologinis turtas','172','17','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Daugiamečiai sodiniai','1720','172','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Daugiamečių sodinių įsigijimo savikaina','17200','1720','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Daugiamečių sodinių tikrosios vertės pokytis (+/−)','17201','1720','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Daugiamečių sodinių vertės sumažėjimas (−)','17209','1720','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Gyvuliai ir kiti gyvūnai','1725','172','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Produktyvieji ir darbiniai gyvuliai','17250','1725','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Produktyviųjų ir darbinių gyvulių įsigijimo savikaina','172500','17250','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Produktyviųjų ir darbinių gyvulių tikrosios vertės pokytis (+/−)','172501','17250','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Produktyviųjų ir darbinių gyvulių vertės sumažėjimas (−)','172509','17250','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Auginami ir penimi gyvuliai ir kiti gyvūnai','17251','1725','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Auginamų ir penimų gyvulių ir kitų gyvūnų įsigijimo savikaina','172510','17251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Auginamų ir penimų gyvulių ir kitų gyvūnų tikrosios vertės pokytis (+/−)','172511','17251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Auginamų ir penimų gyvulių ir kitų gyvūnų vertės sumažėjimas (−)','172519','17251','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kitas turtas','173','17','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito turto įsigijimo savikaina','1730','173','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito turto tikrosios vertės pokytis (+/−)','1731','173','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito turto vertės sumažėjimas (−)','1739','173','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(1,TRUE,'TRUMPALAIKIS TURTAS','2','','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Atsargos','20','2','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Žaliavos, medžiagos ir komplektavimo detalės','201','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žaliavų, medžiagų ir komplektavimo detalių įsigijimo savikaina','2010','201','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žaliavos, medžiagos ir komplektavimo detalės kelyje','2011','201','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žaliavos, medžiagos ir komplektavimo detalės pas trečiuosius asmenis','2012','201','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Žaliavų, medžiagų ir komplektavimo detalių vertės sumažėjimas (−)','2019','201','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Nebaigta produkcija ir vykdomi darbai','202','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Nebaigta produkcija','2020','202','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Nebaigtos produkcijos savikaina','20200','2020','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Nebaigtos produkcijos vertės sumažėjimas (−)','20209','2020','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Vykdomi darbai','2021','202','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Vykdomų darbų savikaina','20210','2021','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Vykdomų darbų vertės sumažėjimas (−)','20219','2021','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Produkcija','203','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Produkcijos savikaina','2030','203','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Produkcija kelyje','2035','203','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Produkcija pas trečiuosius asmenis','2036','203','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Produkcijos vertės sumažėjimas (−)','2039','203','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Pirktos prekės, skirtos perparduoti','204','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirktų prekių, skirtų perparduoti, įsigijimo savikaina','2040','204','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirktos prekės, skirtos perparduoti, kelyje','2045','204','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirktos prekės, skirtos perparduoti, pas trečiuosius asmenis','2046','204','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirktų prekių, skirtų perparduoti, vertės sumažėjimas (−)','2049','204','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Biologinis turtas','205','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Gyvuliai ir kiti gyvūnai','2050','205','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Produktyvieji ir darbiniai gyvuliai','20500','2050','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Produktyviųjų ir darbinių gyvulių įsigijimo savikaina','205000','20500','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Produktyviųjų ir darbinių gyvulių tikrosios vertės pokytis (+/−)','205001','20500','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Produktyviųjų ir darbinių gyvulių vertės sumažėjimas (−)','205009','20500','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Auginami ir penimi gyvuliai ir kiti gyvūnai','20501','2050','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Auginamų ir penimų gyvulių ir kitų gyvūnų įsigijimo savikaina','205010','20501','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Auginamų ir penimų gyvulių ir kitų gyvūnų tikrosios vertės pokytis (+/−)','205011','20501','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Auginamų ir penimų gyvulių ir kitų gyvūnų vertės sumažėjimas (−)','205019','20501','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Pasėliai','2051','205','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pasėlių savikaina','20510','2051','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pasėlių tikrosios vertės pokytis (+/−)','20511','2051','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Pasėlių vertės sumažėjimas (−)','20519','2051','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Ilgalaikis materialusis turtas, skirtas parduoti','206','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ilgalaikio materialiojo turto, skirto parduoti, savikaina','2060','206','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ilgalaikio materialiojo turto, skirto parduoti, vertės sumažėjimas (−)','2069','206','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Nematerialusis turtas, skirtas parduoti','207','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Nematerialiojo turto, skirto parduoti, savikaina','2070','207','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Nematerialiojo turto, skirto parduoti, vertės sumažėjimas (−)','2079','207','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Sumokėti avansai','208','20','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Sumokėti avansai tiekėjams','2080','208','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Užstatas','2084','208','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Sumokėtų avansų vertės sumažėjimas (−)','2089','208','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Per vienus metus gautinos sumos','24','2','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Pirkėjų skolos','241','24','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirkėjų skolų vertė','2410','241','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirkėjų skolų vertės sumažėjimas (−)','2419','241','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įmonių grupės įmonių skolos','242','24','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Patronuojančiosios įmonės skolos','2420','242','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės skolų vertė','24200','2420','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės skolų vertės sumažėjimas (−)','24209','2420','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Patronuojamųjų įmonių skolos','2421','242','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių skolų vertė','24210','2421','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių skolų vertės sumažėjimas (−)','24219','2421','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Asocijuotųjų įmonių skolos','243','24','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Asocijuotųjų įmonių skolų vertė','2430','243','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Asocijuotųjų įmonių skolų vertės sumažėjimas (−)','2439','243','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kitos gautinos sumos','244','24','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Suteiktos paskolos','2440','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Suteiktų paskolų vertė','24400','2440','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Suteiktų paskolų vertės sumažėjimas (−)','24409','2440','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Gautinas pridėtinės vertės mokestis','2441','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš anksto sumokėtas pelno mokestis','2442','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokesčių permokos','2443','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'VSDF skola įmonei','2444','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Iš atskaitingų asmenų gautinos sumos','2445','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš atskaitingų asmenų gautinų sumų vertė','24450','2445','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš atskaitingų asmenų gautinų sumų vertės sumažėjimas (−)','24459','2445','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kitos gautinos skolos','2446','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų gautinos skolų vertė','24460','2446','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų gautinų skolų vertės sumažėjimas (−)','24469','2446','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Su įmonės savininkais susijusios sumos','2447','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Įmonės savininkams avansu išmokėtas pelnas','24471','2447','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Įmonės savininkų asmeniniams poreikiams išmokėtos lėšos','24472','2447','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitos abejotinos skolos (−)','2449','244','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Trumpalaikės investicijos','26','2','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įmonių grupės įmonių akcijos','261','26','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Patronuojančiosios įmonės akcijų vertė','2610','261','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės akcijų įsigijimo savikaina','26100','2610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės akcijų tikrosios vertės pokytis (+/−)','26101','2610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojančiosios įmonės akcijų vertės sumažėjimas (−)','26103','2610','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Patronuojamųjų įmonių akcijų vertė','2611','261','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių akcijų įsigijimo savikaina','26110','2611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių akcijų tikrosios vertės pokytis (+/−)','26111','2611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Patronuojamųjų įmonių akcijų vertės sumažėjimas (−)','26112','2611','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kitos investicijos','262','26','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kitų įmonių nuosavybės vertybiniai popieriai','2620','262','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų įmonių nuosavybės vertybinių popierių įsigijimo savikaina','26200','2620','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų įmonių nuosavybės vertybinių popierių tikrosios vertės pokytis (+/−)','26201','2620','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų įmonių nuosavybės vertybinių popierių vertės sumažėjimas (−)','26209','2620','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Ne nuosavybės vertybiniai popieriai','2621','262','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Iki išpirkimo laikomi ne nuosavybės vertybiniai popieriai','26210','2621','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Iki išpirkimo laikomų ne nuosavybės vertybinių popierių įsigijimo savikaina','262100','26210','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Iki išpirkimo laikomų ne nuosavybės vertybinių popierių amortizuotos savikainos pokytis (+/−)','262101','26210','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Iki išpirkimo laikomų ne nuosavybės vertybinių popierių vertės sumažėjimas (−)','262109','26210','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,TRUE,'Kiti ne nuosavybės vertybiniai popieriai','26211','2621','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Kitų ne nuosavybės vertybinių popierių įsigijimo savikaina','262110','26211','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Kitų ne nuosavybės vertybinių popierių tikrosios vertės pokytis (+/−)','262111','26211','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(6,FALSE,'Kitų ne nuosavybės vertybinių popierių vertės sumažėjimas (−)','262119','26211','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Kiti vertybiniai popieriai','2622','262','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų vertybinių popierių įsigijimo savikaina','26220','2622','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų vertybinių popierių tikrosios vertės pokytis (+/−)','26221','2622','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Kitų vertybinių popierių vertės sumažėjimas (−)','26229','2622','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Terminuotieji indėliai','2623','262','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,TRUE,'Iš išvestinių finansinių priemonių atsiradęs finansinis turtas','2624','262','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš išvestinių finansinių priemonių atsiradusio finansinio turto įsigijimo savikaina','26240','2624','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš išvestinių finansinių priemonių atsiradusio finansinio turto tikrosios vertės pokytis (+/−)','26241','2624','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(5,FALSE,'Iš išvestinių finansinių priemonių atsiradusio finansinio turto vertės sumažėjimas (−)','26249','2624','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Pinigai ir pinigų ekvivalentai','27','2','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Sąskaitos bankuose','271','27','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kasa','272','27','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Pinigai kelyje','273','27','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Pinigų ekvivalentai','274','27','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Įšaldytos lėšos (−)','279','27','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Ateinančių laikotarpių sąnaudos ir sukauptos pajamos','29','2','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ateinančių laikotarpių sąnaudos','291','29','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Sukauptos pajamos','292','29','ASSETS');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(1,TRUE,'NUOSAVAS KAPITALAS','3','','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Kapitalas','30','3','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įstatinis pasirašytasis kapitalas (pagrindinis kapitalas)','301','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Paprastosios akcijos','3011','301','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Privilegijuotosios akcijos','3012','301','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Darbuotojų akcijos','3013','301','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pajai','3014','301','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Pasirašytasis neapmokėtas kapitalas (−)','302','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Savos akcijos (pajai) (−)','303','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Įmonės savininko kapitalas','305','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Turtą, kuris pagal įstatymus gali būti tik valstybės nuosavybė, atitinkantis kapitalas','306','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Centralizuotai valdomą valstybės turtą atitinkantis kapitalas','307','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Savininkų įnašai','308','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Nesumokėti savininkų įnašai (−)','309','30','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,FALSE,'Akcijų priedai','31','3','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Perkainojimo rezervas','32','3','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ilgalaikio materialiojo turto perkainojimo rezervas','321','32','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Finansinio turto perkainojimo rezervas','322','32','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Rezervai','33','3','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Privalomasis arba atsargos (rezervinis) kapitalas','331','33','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Savoms akcijoms įsigyti','332','33','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kiti rezervai','333','33','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Nepaskirstytasis pelnas (nuostoliai)','34','3','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Ataskaitinių metų nepaskirstytasis pelnas (nuostoliai)','341','34','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pelno (nuostolių) ataskaitoje pripažintas ataskaitinių metų grynasis pelnas (nuostoliai)','3411','341','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pelno (nuostolių) ataskaitoje nepripažintas ataskaitinių metų pelnas (nuostoliai)','3412','341','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Ankstesnių metų nepaskirstytasis pelnas (nuostoliai)','342','34','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pelno (nuostolių) ataskaitoje pripažintas ankstesnių metų pelnas (nuostoliai)','3421','342','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pelno (nuostolių) ataskaitoje nepripažintas ankstesnių metų pelnas (nuostoliai)','3422','342','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ankstesnių metų pelnas (nuostoliai) dėl apskaitos politikos keitimo','3423','342','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ankstesnių metų esminių klaidų taisymo pelnas (nuostoliai)','3424','342','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,FALSE,'Bendra sąskaitų suvestinė','390','3','EQUITY');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(1,TRUE,'ĮSIPAREIGOJIMAI','4','','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Dotacijos, subsidijos','40','4','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Su turtu susijusios dotacijos','401','40','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Su pajamomis susijusios dotacijos','402','40','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Atidėjiniai','41','4','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Pensijų ir panašių įsipareigojimų atidėjiniai','411','41','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Mokesčių atidėjiniai','412','41','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kiti atidėjiniai','413','41','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Po vienų metų mokėtinos sumos ir kiti ilgalaikiai įsipareigojimai','42','4','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Skoliniai įsipareigojimai','421','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Skolos pagal ne nuosavybės vertybinius popierius','4210','421','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Lizingo (finansinės nuomos) ar panašūs įsipareigojimai','4211','421','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš išvestinių finansinių priemonių atsiradę įsipareigojimai','4213','421','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kiti skoliniai įsipareigojimai','4214','421','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Skolos kredito įstaigoms','422','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ilgalaikiai įsipareigojimai pagal paskolų sutartis','4220','422','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kiti įsipareigojimai','4221','422','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Gauti avansai','423','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš pirkėjų gauti avansai','4230','423','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš paslaugų gavėjų gauti avansai','4231','423','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Skolos tiekėjams','424','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Pagal vekselius ir čekius mokėtinos sumos','425','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įmonių grupės įmonėms mokėtinos sumos','426','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Patronuojančiajai įmonei mokėtinos sumos','4260','426','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Patronuojamosioms įmonėms mokėtinos sumos','4261','426','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Asocijuotosioms įmonėms mokėtinos sumos','427','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos mokėtinos sumos ir ilgalaikiai įsipareigojimai','428','42','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Per vienus metus mokėtinos sumos ir kiti trumpalaikiai įsipareigojimai','44','4','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Skoliniai įsipareigojimai','440','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Skolos pagal ne nuosavybės vertybinius popierius','4400','440','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Lizingo (finansinės nuomos) ar panašių įsipareigojimų einamųjų metų dalis','4401','440','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš išvestinių finansinių priemonių atsiradę įsipareigojimai','4402','440','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų ilgalaikių skolų einamųjų metų dalis','4403','440','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kiti skoliniai įsipareigojimai','4404','440','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Skolos kredito įstaigoms','441','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Įsipareigojimai pagal trumpalaikių paskolų sutartis','4410','441','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Skolų kredito įstaigoms einamųjų metų dalis','4411','441','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kiti įsipareigojimai','4413','441','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Gauti avansai','442','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš pirkėjų gauti avansai','4420','442','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Iš paslaugų gavėjų gauti avansai','4421','442','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Skolos tiekėjams','443','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Skolos tiekėjams už prekes ir paslaugas','4430','443','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitos skolos tiekėjams','4431','443','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Pagal vekselius ir čekius mokėtinos sumos','444','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įmonių grupės įmonėms mokėtinos sumos','445','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Patronuojančiajai įmonei mokėtinos sumos','4450','445','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Patronuojamosioms įmonėms mokėtinos sumos','4451','445','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Asocijuotosioms įmonėms mokėtinos sumos','446','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Pelno mokesčio įsipareigojimai','447','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pelno mokesčio įsipareigojimai','4470','447','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kiti panašūs įsipareigojimai','4471','447','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Su darbo santykiais susiję įsipareigojimai','448','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinas darbo užmokestis','4480','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinas gyventojų pajamų mokestis','4481','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinos socialinio draudimo įmokos','4482','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinos garantinio fondo įmokos','4483','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitos išmokos darbuotojams','4484','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Atostoginių kaupiniai','4485','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinos privalomojo sveikatos draudimo įmokos','4486','448','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Kitos mokėtinos sumos','449','44','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtini dividendai','4490','449','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinos tantjemos','4491','449','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Mokėtinas pridėtinės vertės mokestis','4492','449','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kiti į biudžetą mokėtini mokesčiai','4493','449','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitos mokėtinos sumos','4494','449','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Įmonės savininkams mokėtinos sumos','4495','449','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Sukauptos sąnaudos ir ateinančių laikotarpių pajamos','49','4','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Sukauptos sąnaudos','491','49','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ateinančių laikotarpių pajamos','492','49','LIABILITIES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(1,TRUE,'PAJAMOS','5','','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Pardavimo pajamos','50','5','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Prekių ir paslaugų pajamos','500','50','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Parduotų prekių pajamos','5000','500','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Suteiktų paslaugų pajamos','5001','500','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Nuolaidos, grąžinimas (−)','509','50','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,FALSE,'Pajamos dėl biologinio turto tikrosios vertės pokyčio','51','5','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Kitõs veiklos pajamos','54','5','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ilgalaikio turto perleidimo pelnas','5400','54','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos pajamos','5401','54','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Investicijų į patronuojančiosios, patronuojamųjų ir asocijuotųjų įmonių akcijas pajamos','55','5','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Investicijų į patronuojančiosios, patronuojamųjų ir asocijuotųjų įmonių akcijas dividendai','5500','55','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Investicijų į patronuojančiosios, patronuojamųjų ir asocijuotųjų įmonių akcijas perleidimo pelnas','5501','55','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Kitų ilgalaikių investicijų ir paskolų pajamos','56','5','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitų ilgalaikių investicijų ir paskolų palūkanų pajamos','5600','56','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitų ilgalaikių investicijų ir paskolų perleidimo pelnas','5601','56','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitų ilgalaikių investicijų dividendai','5604','56','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos pajamos','5609','56','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Kitos palūkanų ir panašios pajamos','58','5','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitų suteiktų paskolų palūkanų pajamos','5802','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Teigiama valiutų kursų pokyčio įtaka','5803','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Baudų ir delspinigių pajamos','5804','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Iš išvestinių finansinių priemonių atsiradęs pelnas','5805','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Investicijų tikrosios vertės padidėjimo pelnas','5808','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Investicijų perleidimo pelnas','5809','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos finansinės ir investicinės veiklos pajamos','5810','58','INCOME');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(1,TRUE,'SĄNAUDOS','6','','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Pardavimo savikaina','60','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Parduotų prekių ir suteiktų paslaugų savikaina','600','60','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Parduotų prekių savikaina','6000','600','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Suteiktų paslaugų savikaina','6001','600','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Įsigytų prekių ir paslaugų savikaina','6002','600','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Tiesioginės gamybos išlaidos','6003','600','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Netiesioginės gamybos išlaidos','6004','600','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Atsargų padidėjimas (sumažėjimas)','6005','600','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Nuolaidos, grąžinimas (−)','609','60','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,FALSE,'Sąnaudos dėl biologinio turto tikrosios vertės pokyčio','61','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Pardavimo sąnaudos','62','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Komisiniai mokesčiai pardavėjams','6200','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Prekybos pastatų ir įrangos vertės nusidėvėjimas','6201','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Paslaugų ir prekių reklamos sąnaudos','6202','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Darbuotojų darbo užmokestis ir su juo susijusios sąnaudos','6203','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Atidėjinių sąnaudos','6204','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos pardavimo sąnaudos','6208','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Gautos nuolaidos (−)','6209','62','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Bendrosios ir administracinės sąnaudos','63','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Nuomos sąnaudos','6300','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Remonto ir eksploatacijos sąnaudos','6301','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Išmokų tretiesiems asmenims sąnaudos','6302','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Draudimo sąnaudos','6303','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Darbuotojų darbo užmokestis ir su juo susijusios sąnaudos','6304','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Tantjemos ir kitos panašios išmokos','6305','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ilgalaikio materialiojo turto vertės nusidėvėjimo sąnaudos','6306','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Nematerialiojo turto vertės amortizacijos sąnaudos','6307','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Veiklos mokesčių sąnaudos','6308','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Nekilnojamojo turto mokesčio sąnaudos','63080','6308','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Neatskaitomo pridėtinės vertės mokesčio sąnaudos','63081','6308','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Aplinkos teršimo mokesčio sąnaudos','63082','6308','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kitų mokesčių sąnaudos','63083','6308','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Turto vertės sumažėjimo sąnaudos','6309','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Pirkėjų skolų vertės sumažėjimo sąnaudos','63090','6309','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Atsargų vertės sumažėjimo sąnaudos','63091','6309','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Nematerialiojo turto vertės sumažėjimo sąnaudos','63092','6309','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Ilgalaikio materialiojo turto vertės sumažėjimo sąnaudos','63093','6309','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Kito turto vertės sumažėjimo sąnaudos','63094','6309','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Atidėjinių sąnaudos','6310','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Baudų ir delspinigių sąnaudos','6311','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos bendrosios ir administracinės sąnaudos','6312','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Gautos nuolaidos (−)','6313','63','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Kitos veiklos sąnaudos','64','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ilgalaikio turto perleidimo nuostoliai','6400','64','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos sąnaudos','6401','64','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Finansinio turto ir trumpalaikių investicijų vertės sumažėjimas','67','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ilgalaikio finansinio turto vertės sumažėjimo sąnaudos','6701','67','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Trumpalaikių investicijų vertės sumažėjimo sąnaudos','6702','67','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Palūkanų ir kitos panašios sąnaudos','68','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,TRUE,'Įmonių grupės įmonėms suteiktų paskolų palūkanų sąnaudos','6800','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Patronuojančiajai įmonei suteiktų paskolų palūkanų sąnaudos','68001','6800','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(4,FALSE,'Patronuojamosioms įmonėms suteiktų paskolų palūkanų sąnaudos','68002','6800','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Asocijuotosioms įmonėms suteiktų paskolų palūkanų sąnaudos','6801','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitų suteiktų paskolų palūkanų sąnaudos','6802','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Neigiama valiutų kursų pokyčio įtaka','6803','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Baudų ir delspinigių sąnaudos','6804','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Iš išvestinių finansinių priemonių atsiradę nuostoliai','6805','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Palūkanų sąnaudos už finansinės nuomos būdu įsigyjamą turtą','6806','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Investicijų tikrosios vertės sumažėjimo nuostoliai','6808','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Investicijų perleidimo nuostoliai','6809','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Kitos finansinės ir investicinės veiklos sąnaudos','6810','68','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(2,TRUE,'Pelno ir panašūs mokesčiai','69','6','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Ataskaitinių metų pelno ir panašūs mokesčiai','6900','69','EXPENSES');
INSERT INTO gl_accounts(depth,"inner",name,"number",parent,type) VALUES(3,FALSE,'Atidėtojo pelno mokesčio sąnaudos (pajamos)','6901','69','EXPENSES');